/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.55
 * Generated at: 2023-09-09 12:29:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.sunilos.p4.ctl.UserListCtl;
import com.sunilos.p4.ctl.ORSView;
import com.sunilos.p4.util.ServletUtility;
import java.util.List;
import java.util.Iterator;
import com.sunilos.p4.bean.UserBean;
import com.sunilos.p4.ctl.BaseCtl;

public final class UserListView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/jsp/ListFooter.jsp", Long.valueOf(1694177074000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.sunilos.p4.ctl.ORSView");
    _jspx_imports_classes.add("com.sunilos.p4.bean.UserBean");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.sunilos.p4.ctl.UserListCtl");
    _jspx_imports_classes.add("java.util.Iterator");
    _jspx_imports_classes.add("com.sunilos.p4.ctl.BaseCtl");
    _jspx_imports_classes.add("com.sunilos.p4.util.ServletUtility");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

   int pageNo = ServletUtility.getPageNo(request);
   int pageSize = ServletUtility.getPageSize(request);
   int index = ((pageNo - 1) * pageSize) + 1;
   
   List list = ServletUtility.getList(request);
   Iterator<UserBean> it = list.iterator();
   
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h1>User List</h1>\r\n");
      out.write("\r\n");
      out.write("<form action=\"");
      out.print(ORSView.USER_LIST_CTL);
      out.write("\" method=\"POST\">\r\n");
      out.write("\r\n");
      out.write("   <input type=\"hidden\" name=\"pageNo\" value=\"");
      out.print(pageNo);
      out.write("\"> \r\n");
      out.write("   <input type=\"hidden\" name=\"pageSize\" value=\"");
      out.print(pageSize);
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("   <div class=\"table-container\">\r\n");
      out.write("      <table width=\"100%\">\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td align=\"center\"><label>FirstName :</label> <input\r\n");
      out.write("               type=\"text\" name=\"firstName\"\r\n");
      out.write("               value=\"");
      out.print(ServletUtility.getParameter("firstName", request));
      out.write("\">\r\n");
      out.write("               &emsp; <label>LoginId:</label> <input type=\"text\" name=\"login\"\r\n");
      out.write("                  value=\"");
      out.print(ServletUtility.getParameter("login", request));
      out.write("\">\r\n");
      out.write("               <input  class=\"primary-btn\" type=\"submit\" name=\"operation\" value=\"");
      out.print(BaseCtl.OP_SEARCH );
      out.write("\">&nbsp;\r\n");
      out.write("               <a  class=\"success-btn\" href=\"UserCtl\">Add</a>&nbsp;\r\n");
      out.write("               <input  class=\"danger-btn\" type=\"submit\" name=\"operation\" value=\"");
      out.print(BaseCtl.OP_DELETE);
      out.write("\">	\r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("      <br>\r\n");
      out.write("      <table class=\"border-separated-table\">\r\n");
      out.write("         <tr>\r\n");
      out.write("            <th>Select</th>\r\n");
      out.write("            <th>SNo</th>\r\n");
      out.write("            <th>FirstName</th>\r\n");
      out.write("            <th>LastName</th>\r\n");
      out.write("            <th>LoginId</th>\r\n");
      out.write("            <th>Gender</th>\r\n");
      out.write("            <th>DOB</th>\r\n");
      out.write("            <th>Edit</th>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td colspan=\"8\"><font color=\"red\">");
      out.print(ServletUtility.getErrorMessage(request));
      out.write("</font></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         ");

            while (it.hasNext()) {
            	UserBean bean = it.next();
            
      out.write("\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td><input type=\"checkbox\" name=\"ids\" value=\"");
      out.print(bean.getId());
      out.write("\"></td>\r\n");
      out.write("            <td>");
      out.print(index++);
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print(bean.getFirstName());
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print(bean.getLastName());
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print(bean.getLogin());
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print(bean.getGender());
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print(bean.getDob());
      out.write("</td>\r\n");
      out.write("            <td><a class=\"primary-btn\" href=\"UserCtl?id=");
      out.print(bean.getId());
      out.write("\">Edit</a></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         ");

            }
            
      out.write("\r\n");
      out.write("      </table>\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("<table width=\"100%\">\r\n");
      out.write("   <tr>\r\n");
      out.write("      <td align=\"center\" > <<\r\n");
      out.write("      	<input  class=\"primary-btn\"  type=\"submit\" name=\"operation\" value=\"");
      out.print(BaseCtl.OP_PREVIOUS);
      out.write("\"> || \r\n");
      out.write("      	<input  class=\"primary-btn\" type=\"submit\" name=\"operation\" value=\"");
      out.print(BaseCtl.OP_NEXT);
      out.write("\"> >>\r\n");
      out.write("      </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("</table>");
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("</form>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
